/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

//Runtime: 1 ms & Memory: 40.8 MB

class Solution {
    public char findTheDifference(String s, String t) {
        int sumS = 0;
        int sumT = 0;
        int len = s.length();

        for(int i=0; i<len; i++){
            sumS += s.charAt(i);
            sumT += t.charAt(i);
        }

        sumT += t.charAt(t.length()-1);

        return (char) (sumT-sumS);
    }
}
